# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Intermedia Code Challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Intermedia Code Challenge
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'PureLayout'


  target 'Intermedia Code ChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Intermedia Code ChallengeUITests' do
    # Pods for testing
  end

end
